name: kazoku_pet_store
description: A simple Kazoku Pet Store Flutter app (UI-first, Material 3)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  battery_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_material_color_picker: ^1.2.0
  http: ^1.6.0
  http_parser: ^4.1.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  provider: ^6.0.5
  sensors_plus: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter